Traceback (most recent call last):
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\herbst\Anaconda3\envs\mypython37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
wl(f, ['u l'])             # update lens
wl(f, ['chg 2'])           # change surface 2
wl(f, ['rd 40.94'])        # radius to value
wl(f, ['chg 3'])           # change surface 3
wl(f, ['th 11.05']) 
wl(f, ['ins 1'])           # insert surface at 1
wl(f, ['del 1'])           # delete surface at 1
wl(f, ['eos'])             # exit update lens
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_3664\1498240027.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mwl[0m[1;33m([0m[0mf[0m[1;33m,[0m [1;33m[[0m[1;34m'u l'[0m[1;33m][0m[1;33m)[0m             [1;31m# update lens[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mwl[0m[1;33m([0m[0mf[0m[1;33m,[0m [1;33m[[0m[1;34m'chg 2'[0m[1;33m][0m[1;33m)[0m           [1;31m# change surface 2[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mwl[0m[1;33m([0m[0mf[0m[1;33m,[0m [1;33m[[0m[1;34m'rd 40.94'[0m[1;33m][0m[1;33m)[0m        [1;31m# radius to value[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mwl[0m[1;33m([0m[0mf[0m[1;33m,[0m [1;33m[[0m[1;34m'chg 3'[0m[1;33m][0m[1;33m)[0m           [1;31m# change surface 3[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mwl[0m[1;33m([0m[0mf[0m[1;33m,[0m [1;33m[[0m[1;34m'th 11.05'[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp\ipykernel_3664\191631149.py[0m in [0;36mwl[1;34m(file, L)[0m
[0;32m      3[0m     [0mFunction[0m [1;32mfor[0m [0mwriting[0m [0ma[0m [0mline[0m [1;32min[0m [0ma[0m [0mfile[0m[1;33m.[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     """   
[1;32m----> 5[1;33m     [0mfile[0m[1;33m.[0m[0mwritelines[0m[1;33m([0m[0mL[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m     [0mfile[0m[1;33m.[0m[0mwrite[0m[1;33m([0m[1;34m"\n"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: I/O operation on closed file.
ValueError: I/O operation on closed file.

